### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by lakaniemi** [Tietokilta/tikweb-frontend#3]
## Kuvaus

CI pystyyn, joka ajaa sekä testit, että lintterin. Tulokset pitää saada jotenkin fiksusti näkyviin ainakin pullareihin, mutta varmaan fiksua ajaa tyyliin jokaiselle commitille. CI-alustana käytetään GitHub Actionsia.

Dependaa testien ja lintterin osalta issuesta #2

Tämän voi toteuttaa myös ilman testisetuppia, mutta silloin olisi hyvä luoda jokin placeholderi testien ajamiselle, joka voidaan ottaa helposti käyttöön, kun testien ajoympäristö on konfiguroitu.

## Taskit

- [x] CI:n pystytys
- [x] Testien ajo CI:ssä
- [x] Lintterin ajo CI:ssä
- [x] Tulokset nähtävissä Pull Requesteissa (ja commiteissa?)

**Comment by tuomorphism** [comment]
Doned 👍
