### ISSUE TITLE
CI/CD build for the site

### ISSUE THREAD

**Issue by lakaniemi** [Tietokilta/tikweb-frontend#4]
## Description

We need a CI build that builds the static files with production settings to be served from the cloud. At this point we don't have to care about domains, just that the website ends up accessible in the Azure cloud.

Building will happen with every commit at this point. In the future, we must also have the option of building based on webhooks, such as when updates are made in the CMS.

Depends on #3 

## Tasks

- [ ] Gatsby build in CI to get the static files
- [ ] CD config to upload the resulting files to Azure Blob Storage

**Comment by PurkkaKoodari** [comment]
Done in #19
